name: todolist
description: "A powerful toy of TODO-List"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logger: ^2.5.0
  http: ^1.1.0
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.3.0
  package_info_plus: ^8.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.2
  excel: ^4.0.6
  file_picker: ^10.3.3
  syncfusion_flutter_xlsio: ^29.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/splash.png"
  android: true
  color_android: "#f6eee4"
  android_12:
    image: "assets/icon/splash.png"
  ios: true
  image_ios: "assets/icon/splash.png"
  image_android: "assets/icon/splash.png"
